#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"


[[ "$#" == 2 ]] || log usage "build-hw-config PLATFORM PROJ_DIR" \
  "available platforms are: zynq7000, zedboard, ultrascale, coraz7"

PLATFORM="$1"
_ensure-exists dir PROJ_DIR "$2"
_ensure-exists file PROJ_FILE "$PROJ_DIR/workspace/"*.xpr
_mkdir-if-missing "$PROJ_DIR/hardware_configuration"

vivado -nolog -nojournal -mode batch \
    -source "$UTILS_ROOT/tcl-lib/vivado_all.tcl" "$PROJ_FILE" \
    -tclargs "$PROJ_DIR/hardware_configuration"
