#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"


[[ "$#" == 2 ]] || log usage "build-hello-world PLATFORM PROJ_DIR" \
  "available platforms are: zynq7000, zedboard, ultrascale, coraz7"

PLATFORM="$1"
_ensure-exists dir PROJ_DIR "$2"
_ensure-exists file HELLO_WORLD_CREATE "$UTILS_ROOT/tcl-lib/vitis_hello_world_$PLATFORM.tcl"
_ensure-exists file HELLO_WORLD_BUILD "$UTILS_ROOT/tcl-lib/vitis_build_hello_world.tcl"
_ensure-exists file XSA "$PROJ_DIR/hardware_configuration/hw_export.xsa"

if [[ -d "$PROJ_DIR/application_configuration" ]] || [[ -d "$PROJ_DIR/application_export" ]]
then
  rm --recursive --force -- "$PROJ_DIR/"{application_configuration,application_export}
fi

_mkdir-if-missing "$PROJ_DIR/"{application_configuration,application_export}


xsct "$HELLO_WORLD_CREATE" "$PROJ_DIR/application_configuration" "$XSA"


cp --force "$UTILS_ROOT/utils/helloworld.c" "$PROJ_DIR/application_configuration/${PLATFORM}_hello_world/src/"

xsct "$HELLO_WORLD_BUILD" "$PROJ_DIR/application_configuration" "$PLATFORM"

cp "$PROJ_DIR/application_configuration/${PLATFORM}_hello_world/Release/${PLATFORM}_hello_world.elf" "$PROJ_DIR/application_export/${PLATFORM}_application.elf"
