#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"

help()
{   
log usage "build-hw-config [Arguments] [Options]
Arguments:        
    PROJ_DIR    project directory

Options:   
    -c, --carrier CARRIER    devboard, fcc"
}

if [[ $# -eq 0 ]]
then
  help
fi

POSITIONAL=() 
while [[ $# -gt 0 ]]; do
  case $1 in
    -c|--carrier)
        CARRIER=$2
        shift 2
        ;;
    -h|--help)
        help
        ;;
    *)
        POSITIONAL+=($1)
        shift
        ;;
  esac
done

set -- "${POSITIONAL[@]}"

_ensure-exists dir PROJ_DIR "$1"
_ensure-exists file PROJ_FILE "$PROJ_DIR/workspace/"*.xpr
_ensure-exists file PROJ_CFG "$PROJ_DIR/project.cfg"
_mkdir-if-missing "$PROJ_DIR/hardware_configuration"

PLATFORM=$(grep "platform=" "$PROJ_CFG" | cut -d'=' -f2)

case "$PLATFORM" in 
    "zynq7000"|"ultrascale")
        case "$CARRIER" in 
            "devboard"|"fcc")
                ;;
            "")
                log error "please specify a carrier board: devboard, fcc"
                help
                return 1
                ;;
            *)
                log error "unsupported carrier $CARRIER" 1
                ;;
        esac
        ;;
    "zedboard"|"coraz7")
        CARRIER="$PLATFORM"
        ;;
    *)
        log error "unsupported platform $PLATFORM" 1
        ;;
esac

sed -i "2s/.*/"carrier=$CARRIER"/" "$PROJ_CFG"

vivado -nolog -nojournal -mode batch \
    -source "$UTILS_ROOT/tcl-lib/vivado_all.tcl" "$PROJ_FILE" \
    -tclargs "$PROJ_DIR" "$PROJ_DIR/hardware_configuration" "$CARRIER"

unzip "${PROJ_DIR}/hardware_configuration/${CARRIER}_hw_export.xsa" -d "${PROJ_DIR}/hardware_configuration/extract_tmp"

case "$PLATFORM" in
    "zynq7000"|"zedboard"|"coraz7")
        cp --force "${PROJ_DIR}/hardware_configuration/extract_tmp/ps7_init.tcl" "${PROJ_DIR}/hardware_configuration/"
        ;;
    "ultrascale")        
        cp --force "${PROJ_DIR}/hardware_configuration/extract_tmp/psu_init.tcl" "${PROJ_DIR}/hardware_configuration/"        
        ;;
    *)
        log error "unsupported platform $PLATFORM" 1
        ;;
esac

rm -r "${PROJ_DIR}/hardware_configuration/extract_tmp"
