#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"


[[ "$#" == 3 ]] || log usage "create-project TEMPLATE PROJ_DIR PROJ_NAME" \
  "available TEMPLATEs are: zynq7000, ultrascale, zedboard, coraz7"

_ensure-exists file SCRIPT "$UTILS_ROOT/templates/$1.tcl"
PROJ_DIR="$2"
PROJ_NAME="$3"
_ensure-exists-not "$PROJ_DIR/$PROJ_NAME" "Please delete existing project..."
_mkdir-if-missing "$PROJ_DIR/$PROJ_NAME/"{workspace,constr,hdl,scripts}

cp "$UTILS_ROOT/templates/.gitignore" "$PROJ_DIR/$PROJ_NAME"
echo -e "# README for the '$PROJ_NAME' FPGA project\n" > "$PROJ_DIR/$PROJ_NAME/README.md"

_update-wrapper "$PROJ_DIR" "$PROJ_NAME"

vivado -nolog -nojournal -mode batch -source "$SCRIPT" -tclargs "$PROJ_DIR" "$PROJ_NAME"
