#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"


[[ "$#" == 3 ]] || log usage "jtag-boot HW_PLATFORM PROJ_DIR ELF" \
  "available hw platforms are: zynq7000, coraz7, zedboard, ultrascale"

HW_PLATFORM="$1"
_ensure-exists file SCRIPT "$UTILS_ROOT/tcl-lib/jtag_boot/${HW_PLATFORM}_init.tcl"
_ensure-exists dir PROJ_DIR "$2"
_ensure-exists file XSA "$(find "$PROJ_DIR" -name hw_export.xsa | head -n 1)"
_ensure-exists file ELF "$3"

XSA_TMP_DIR
XSA_TMP_DIR=$(mktemp --directory -- "/tmp/$HW_PLATFORM-xsa-XXXXXXXXXX")
unzip -d "$XSA_TMP_DIR" -qq -- "$XSA"
log info "extracted XSA to $XSA_TMP_DIR"

_ensure-exists file BITSTREAM "$XSA_TMP_DIR/hw_export.bit"

# the different HW platforms differ in their initialization, thus a switch case
case "$HW_PLATFORM" in
  "zynq7000"|"zedboard"|"coraz7")
    _ensure-exists file PS7 "$XSA_TMP_DIR/ps7_init.tcl"

    xsct "$SCRIPT" "$PS7" "$BITSTREAM" "$XSA" "$ELF"
  ;;

  "ultrascale")
    _ensure-exists file PMUFW "$(find "$PROJ_DIR" -name pmufw_ultrascale.elf | head -n 1)"
    _ensure-exists file FSBL "$(find "$PROJ_DIR" -name fsbl_ultrascale.elf | head -n 1)"
    _ensure-exists file ZYNQMP_UTILS "$(find "$UTILS_ROOT/tcl-lib" -name zynqmp_utils.tcl | head -n 1)"

    xsct "$SCRIPT" "$BITSTREAM" "$XSA" "$PMUFW" "$FSBL" "$ZYNQMP_UTILS" "$ELF"
  ;;

  *)
    log error "unsupported platform $HW_PLATFORM" 1
  ;;
esac

rm --recursive -- "$XSA_TMP_DIR"
