#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"

help()
{   
log usage "jtag-boot [Arguments]
Arguments:    
    PROJ_DIR    project directory
    ELF         application .elf file
Options:
    -b, --bootloader  BOOTLOADER pass u-boot if this is loaded"
}

if [[ $# -eq 0 ]]
then
  help
fi

POSITIONAL=() 
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
        help
        ;;
    -b|--bootloader)
        BOOTLOADER=$2
        shift 2
        ;;
    *)
        POSITIONAL+=($1)
        shift
        ;;
  esac
done

set -- "${POSITIONAL[@]}"

if [[ $# -lt 2 ]]
then
  help
fi

_ensure-exists dir PROJ_DIR "$1"
_ensure-exists file ELF "$2"
_ensure-exists file PROJ_CFG "$PROJ_DIR/project.cfg"

PLATFORM=$(grep "platform=" "$PROJ_CFG" | cut -d'=' -f2)
CARRIER=$(grep "carrier=" "$PROJ_CFG" | cut -d'=' -f2)



_ensure-exists file BITSTREAM "$PROJ_DIR/hardware_configuration/"$CARRIER"_bitstream_export.bit"

case "$PLATFORM" in
  "zynq7000"|"zedboard"|"coraz7")
    _ensure-exists file PS7 "$PROJ_DIR/hardware_configuration/ps7_init.tcl"
    _ensure-exists file XSA "$PROJ_DIR/hardware_configuration/"$CARRIER"_hw_export.xsa"
    _ensure-exists file SCRIPT "$UTILS_ROOT/tcl-lib/jtag_boot/${PLATFORM}_init.tcl"
    xsct "$SCRIPT" "$PS7" "$BITSTREAM" "$XSA" "$ELF"
    ;;

  "ultrascale")
    _ensure-exists file PMUFW "$PROJ_DIR/bootloader_export/fsbl/pmufw_ultrascale.elf"
    _ensure-exists file FSBL "$PROJ_DIR/bootloader_export/fsbl/fsbl_jtag_ultrascale.elf"
    _ensure-exists file PSU "$PROJ_DIR/hardware_configuration/psu_init.tcl"
    
    case "$BOOTLOADER" in
      "u-boot")
        _ensure-exists file ATF "$PROJ_DIR/bootloader_export/u-boot/bl31.elf"
        _ensure-exists file SYS_DTB "$PROJ_DIR/bootloader_export/u-boot/system.dtb"
        _ensure-exists file SCRIPT "$UTILS_ROOT/tcl-lib/jtag_boot/${PLATFORM}_init_u_boot.tcl"
        xsct "$SCRIPT" "$BITSTREAM" "$PMUFW" "$PSU" "$FSBL" "$SYS_DTB" "$ELF" "$ATF"
        ;;
      *)
        _ensure-exists file SCRIPT "$UTILS_ROOT/tcl-lib/jtag_boot/${PLATFORM}_init.tcl"
        xsct "$SCRIPT" "$BITSTREAM" "$PMUFW" "$PSU" "$FSBL" "$ELF"
        ;;
    esac    
    ;;
  *)
    log error "unsupported platform $PLATFORM" 1
    ;;
esac
