#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"

help()
{   
log usage "program-flash [Arguments]
Arguments:        
    DIR    project directory"    
}

if [[ $# -eq 0 ]]
then
  help
fi

POSITIONAL=() 
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
        help
        ;;
    *)
        POSITIONAL+=($1)
        shift
        ;;
  esac
done

set -- "${POSITIONAL[@]}"

if [[ $# -lt 1 ]]
then
  help
fi

_ensure-exists dir DIR "$1"
_ensure-exists file PROJ_CFG "$DIR/project.cfg"
_ensure-exists file IMAGE "$DIR/boot_image/BOOT.bin"

PLATFORM=$(grep "platform=" "$PROJ_CFG" | cut -d'=' -f2)
#CARRIER=$(grep "carrier=" "$PROJ_CFG" | cut -d'=' -f2)

_ensure-exists file FSBL_FLASH "$DIR/bootloader_export/fsbl/fsbl_flash_$PLATFORM.elf"

case "$PLATFORM" in
    "zynq7000")
        hw_server -d -I 30 -s tcp:localhost:3121
        
        program_flash -f "$IMAGE" -fsbl "$FSBL_FLASH" -flash_type qspi-x4-single -blank_check -verify -url tcp:localhost:3121

        echo 
        echo "### Flash operation done ###"
        echo "- power cycle the board, connect to the board console and stop autoboot"
        echo "- board console: "env default -f -a""
        echo "- board console: "setenv serverip "<"your-server-ip-address">"""
        echo "- board console: "setenv updateFlag true""
        echo "- board console: "saveenv""
        echo
        ;;
    *)
        log error "Program Flash for $PLATFORM is not supported." 1
        ;;
esac
