#!/usr/bin/env bash

UTILS_ROOT=$( cd "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd )
source "$UTILS_ROOT/commands/lib.sh"

help()
{   
log usage "restore [Arguments]
Arguments:        
    PROJ_DIR    project directory"    
}

if [[ $# -eq 0 ]]
then
  help
fi

POSITIONAL=() 
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
        help
        ;;
    *)
        POSITIONAL+=($1)
        shift
        ;;
  esac
done

set -- "${POSITIONAL[@]}"

if [[ $# -lt 1 ]]
then
  help
fi

_ensure-exists dir PROJ_DIR "$1"
_ensure-exists file SCRIPT "$PROJ_DIR/scripts/restore.tcl"
_ensure-exists-not "$PROJ_DIR/workspace" "The workspace '$PROJ_DIR/workspace/' already exists" \
  "Please delete it manually before restoring the project."

pushd "$PROJ_DIR" || return 1
vivado -nolog -nojournal -mode batch -source "$SCRIPT"
[[ -d ".Xil/" ]] && rm -r .Xil/
popd
