# Constraintsfile for Devboard-LaneCommanding

set_property PACKAGE_PIN C4 [get_ports UART_3_TX]
set_property PACKAGE_PIN C6 [get_ports UART_3_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_3_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_3_RX]

set_property PACKAGE_PIN D5 [get_ports UART_4_TX]
set_property PACKAGE_PIN B7 [get_ports UART_4_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_4_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_4_RX]

set_property PACKAGE_PIN B3 [get_ports UART_5_TX]
set_property PACKAGE_PIN B6 [get_ports UART_5_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_5_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_5_RX]

set_property PACKAGE_PIN B4 [get_ports UART_6_TX]
set_property PACKAGE_PIN E4 [get_ports UART_6_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_6_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_6_RX]

set_property PACKAGE_PIN B1 [get_ports UART_7_TX]
set_property PACKAGE_PIN U18 [get_ports UART_7_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_7_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_7_RX]

set_property PACKAGE_PIN AB22 [get_ports UART_8_TX]
set_property PACKAGE_PIN U17 [get_ports UART_8_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_8_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_8_RX]

set_property PACKAGE_PIN C8 [get_ports SPI_0_CLK]
set_property PACKAGE_PIN A4 [get_ports SPI_0_MOSI]
set_property PACKAGE_PIN G3 [get_ports SPI_0_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_MISO]

set_property PACKAGE_PIN E8 [get_ports SPI_1_CLK]
set_property PACKAGE_PIN A7 [get_ports SPI_1_MOSI]
set_property PACKAGE_PIN G2 [get_ports SPI_1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_MISO]

set_property PACKAGE_PIN E5 [get_ports CAN_0_TX]
set_property PACKAGE_PIN G8 [get_ports CAN_0_RX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_RX]

set_property PACKAGE_PIN G4 [get_ports CAN_1_TX]
set_property PACKAGE_PIN G7 [get_ports CAN_1_RX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_RX]

set_property PACKAGE_PIN V18 [get_ports UART_A_TX]
set_property PACKAGE_PIN V19 [get_ports UART_A_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_A_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_A_RX]

set_property PACKAGE_PIN D8 [get_ports SPI_A_CLK]
set_property PACKAGE_PIN A6 [get_ports SPI_A_MOSI]
set_property PACKAGE_PIN G1 [get_ports SPI_A_MISO]
set_property PACKAGE_PIN F7 [get_ports {SPI_A_CS[0]}]
set_property PACKAGE_PIN E7 [get_ports {SPI_A_CS[1]}]
set_property PACKAGE_PIN H1 [get_ports {SPI_A_CS[2]}]
set_property PACKAGE_PIN D7 [get_ports {SPI_A_CS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_A_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_A_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_A_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_A_CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_A_CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_A_CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_A_CS[3]}]

set_property PACKAGE_PIN B8 [get_ports ext_spi_clk_o]
set_property IOSTANDARD LVCMOS33 [get_ports ext_spi_clk_o]

set_property PACKAGE_PIN D2 [get_ports {DRDY_A1[0]}]
set_property PACKAGE_PIN E2 [get_ports {DRDY_A2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DRDY_A1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DRDY_A2[0]}]

set_property PACKAGE_PIN H4 [get_ports {DataEnable_GPIO[0]}]
set_property PACKAGE_PIN H3 [get_ports {DataEnable_GPIO[1]}]
set_property PACKAGE_PIN F2 [get_ports {DataEnable_GPIO[2]}]
set_property PACKAGE_PIN C3 [get_ports {DataEnable_GPIO[3]}]
set_property PACKAGE_PIN D3 [get_ports {DataEnable_GPIO[4]}]
set_property PACKAGE_PIN A2 [get_ports {DataEnable_GPIO[5]}]
set_property PACKAGE_PIN AA11 [get_ports {DataEnable_GPIO[6]}]
set_property PACKAGE_PIN C1 [get_ports {DataEnable_GPIO[7]}]
set_property PACKAGE_PIN D1 [get_ports {DataEnable_GPIO[8]}]
set_property PACKAGE_PIN AA19 [get_ports {DataEnable_GPIO[9]}]
set_property PACKAGE_PIN W17 [get_ports {DataEnable_GPIO[10]}]
set_property PACKAGE_PIN V11 [get_ports {DataEnable_GPIO[11]}]
set_property PACKAGE_PIN Y12 [get_ports {DataEnable_GPIO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[12]}]

set_property PACKAGE_PIN W13 [get_ports SPI_FLASH_A_CLK]
set_property PACKAGE_PIN AB12 [get_ports SPI_FLASH_A_DQ0]
set_property PACKAGE_PIN AA12 [get_ports SPI_FLASH_A_DQ1]
set_property PACKAGE_PIN W15 [get_ports SPI_FLASH_A_DQ2]
set_property PACKAGE_PIN V15 [get_ports SPI_FLASH_A_DQ3]
set_property PACKAGE_PIN V16 [get_ports {SPI_FLASH_A_CS[0]}]
set_property PACKAGE_PIN T17 [get_ports {SPI_FLASH_A_CS[1]}]
set_property PACKAGE_PIN R17 [get_ports {SPI_FLASH_A_CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_A_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_A_DQ0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_A_DQ1]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_A_DQ2]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_A_DQ3]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_A_CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_A_CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_A_CS[2]}]

set_property PACKAGE_PIN J3 [get_ports LED_1_IN]
set_property PACKAGE_PIN U12 [get_ports LED_1_OUT]
set_property PACKAGE_PIN K8 [get_ports LED_2_IN]
set_property PACKAGE_PIN U11 [get_ports LED_2_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports LED_1_IN]
set_property IOSTANDARD LVCMOS33 [get_ports LED_1_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports LED_2_IN]
set_property IOSTANDARD LVCMOS33 [get_ports LED_2_OUT]
