# Constraintsfile for FCC-LaneMonitoring

set_property PACKAGE_PIN D5 [get_ports UART_3_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_3_RX]

set_property PACKAGE_PIN C4 [get_ports UART_3_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_3_commandingOutput_RX]

set_property PACKAGE_PIN G2 [get_ports UART_4_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_4_RX]

set_property PACKAGE_PIN G3 [get_ports UART_4_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_4_commandingOutput_RX]

set_property PACKAGE_PIN A4 [get_ports UART_5_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_5_RX]

set_property PACKAGE_PIN A5 [get_ports UART_5_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_5_commandingOutput_RX]

set_property PACKAGE_PIN F1 [get_ports UART_6_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_6_RX]

set_property PACKAGE_PIN F2 [get_ports UART_6_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_6_commandingOutput_RX]

set_property PACKAGE_PIN A6 [get_ports UART_7_commandingOutput_RX]
set_property PACKAGE_PIN A7 [get_ports UART_7_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_7_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_7_RX]

set_property PACKAGE_PIN B6 [get_ports UART_8_commandingOutput_RX]
set_property PACKAGE_PIN B7 [get_ports UART_8_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_8_commandingOutput_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_8_RX]

set_property PACKAGE_PIN E2 [get_ports SPI_0_CLK]
set_property PACKAGE_PIN B8 [get_ports SPI_0_MOSI]
set_property PACKAGE_PIN C8 [get_ports SPI_0_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_MISO]

set_property PACKAGE_PIN H1 [get_ports SPI_1_CLK]
set_property PACKAGE_PIN G8 [get_ports SPI_1_MOSI]
set_property PACKAGE_PIN G7 [get_ports SPI_1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_1_MISO]

set_property PACKAGE_PIN E7 [get_ports CAN_0_TX]
set_property PACKAGE_PIN F7 [get_ports CAN_0_RX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_RX]

set_property PACKAGE_PIN E5 [get_ports CAN_1_TX]
set_property PACKAGE_PIN F5 [get_ports CAN_1_RX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_TX]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_RX]

set_property PACKAGE_PIN AB18 [get_ports UART_B_TX]
set_property PACKAGE_PIN AB19 [get_ports UART_B_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_B_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_B_RX]

set_property PACKAGE_PIN AB17 [get_ports SPI_B_CLK]
set_property PACKAGE_PIN Y19 [get_ports SPI_B_MOSI]
set_property PACKAGE_PIN Y18 [get_ports SPI_B_MISO]
set_property PACKAGE_PIN Y14 [get_ports {SPI_B_CS[0]}]
set_property PACKAGE_PIN AA19 [get_ports {SPI_B_CS[1]}]
set_property PACKAGE_PIN Y15 [get_ports {SPI_B_CS[2]}]
set_property PACKAGE_PIN W18 [get_ports {SPI_B_CS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_B_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_B_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_B_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_B_CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_B_CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_B_CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_B_CS[3]}]

set_property PACKAGE_PIN AA15 [get_ports {DRDY_B1[0]}]
set_property PACKAGE_PIN AA20 [get_ports {DRDY_B2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DRDY_B1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DRDY_B2[0]}]

set_property PACKAGE_PIN D8 [get_ports {DataEnable_GPIO[0]}]
set_property PACKAGE_PIN F6 [get_ports {DataEnable_GPIO[1]}]
set_property PACKAGE_PIN C6 [get_ports {DataEnable_GPIO[2]}]
set_property PACKAGE_PIN H3 [get_ports {DataEnable_GPIO[3]}]
set_property PACKAGE_PIN H4 [get_ports {DataEnable_GPIO[4]}]
set_property PACKAGE_PIN C5 [get_ports {DataEnable_GPIO[5]}]
set_property PACKAGE_PIN AB22 [get_ports {DataEnable_GPIO[6]}]
set_property PACKAGE_PIN G6 [get_ports {DataEnable_GPIO[7]}]
set_property PACKAGE_PIN E8 [get_ports {DataEnable_GPIO[8]}]
set_property PACKAGE_PIN AB21 [get_ports {DataEnable_GPIO[9]}]
set_property PACKAGE_PIN U17 [get_ports {DataEnable_GPIO[10]}]
set_property PACKAGE_PIN U18 [get_ports {DataEnable_GPIO[11]}]
set_property PACKAGE_PIN V15 [get_ports {DataEnable_GPIO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataEnable_GPIO[12]}]

set_property PACKAGE_PIN AB13 [get_ports SPI_FLASH_B_CLK]
set_property PACKAGE_PIN T17 [get_ports SPI_FLASH_B_DQ0]
set_property PACKAGE_PIN V13 [get_ports SPI_FLASH_B_DQ1]
set_property PACKAGE_PIN R17 [get_ports SPI_FLASH_B_DQ2]
set_property PACKAGE_PIN W15 [get_ports SPI_FLASH_B_DQ3]
set_property PACKAGE_PIN V14 [get_ports {SPI_FLASH_B_CS[0]}]
set_property PACKAGE_PIN U12 [get_ports {SPI_FLASH_B_CS[1]}]
set_property PACKAGE_PIN U11 [get_ports {SPI_FLASH_B_CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_B_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_B_DQ0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_B_DQ1]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_B_DQ2]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_FLASH_B_DQ3]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_B_CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_B_CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_FLASH_B_CS[2]}]

set_property PACKAGE_PIN J3 [get_ports LED21_IN]
set_property PACKAGE_PIN D3 [get_ports LED21_OUT]
set_property PACKAGE_PIN K8 [get_ports LED22_IN]
set_property PACKAGE_PIN C3 [get_ports LED22_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports LED21_IN]
set_property IOSTANDARD LVCMOS33 [get_ports LED21_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports LED22_IN]
set_property IOSTANDARD LVCMOS33 [get_ports LED22_OUT]
